# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qII1dquy9HwE8ix_bhYwoNhasze5H1B1
"""

import numpy as np
import pandas as pd

dict1={
    "name":['jahnavi','annu','prashant','nisha'],
    "age":[34,56,71,23],
    "city":['rampur','varanasi','kolkata','bareilly']
}

df=pd.DataFrame(dict1)

df

df.to_csv('family.csv')

df.head()

df.head(2)

df.describe()



"""pandas has two data structures- series and dataframe"""



"""series- one dimensional array with indexer

dataframe- tabular spreadsheet like structure, two dimensional
"""

type(df)

